name: Lint source code
on: push

jobs:
  es-lint:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Update source code
        run: npm run lint

      - shell: pwsh
        # Give an id to the step, so we can reference it later
        id: check_file_changed
        run: |
          # Diff HEAD with the previous commit
          $diff = git diff --name-only HEAD^ HEAD
          
          # Check if a file under docs/ or with the .md extension has changed (added, modified, deleted)
          $SourceDiff = $diff | Where-Object { $_ -match '^src/' -or $_ -match '^__tests__/' }
          $HasDiff = $SourceDiff.Length -gt 0
          
          # Set the output named "docs_changed"
          Write-Host "::set-output name=docs_changed::$HasDiff"

  conditional_job:
    runs-on: ubuntu-latest
    needs: [ es-lint ]
    if: needs.es-lint.outputs.docs_changed == 'True'
    steps:
      - name: Setting Github user.email
        run: git config --global user.email "shobekhan@yahoo.com"

      - name: Setting Github user.name
        run: git config --global user.name "SB"

      - name: Adding fixes for committing
        run: git add .

      - name: Committing ESLint fixes
        run: git commit -m "fixed ESLint issues"

      - name: Pushing fixes to current PR branch
        run: git push
