name: Lint source code
on: push

jobs:
  es-lint:
    runs-on: ubuntu-latest
    outputs:
      docs_changed: ${{ steps.check_file_changed.outputs.docs_changed }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          # Checkout as many commits as needed for the diff
          fetch-depth: 2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Update source code
        run: npm run lint

      - name: Give proper permissions
        run: chmod 777 ./.githib/workflows/commit-lint-files.sh
        shell: bash

      - name: Push linted TS files
        run: ./commit-lint-files.sh
        shell: bash
